### ISSUE TITLE
Any soultion for Convert Cobie file to Ifc ?

### ISSUE THREAD

**Issue by castronelson** [xBimTeam/XbimCobieExpress#10]
Any possibilities to Convert Cobie file to Ifc.

**Comment by andyward** [comment]
Maybe take a look at https://github.com/xBimTeam/XbimExchange/tree/master/Xbim.Exchanger/COBieLiteToIfc

I can't speak for its completeness, but you can test it out in the Xbim.COBieLiteUK.Client windows app to see if it suits your purpose.

Because COBie is a subset of IFC (and most COBie files contain only maintained assets), you probably need to set your expectations low in terms what the output IFC will be like.
